# Universidades Chilenas
puts '[+] Agregando universidades'
University.create!(name:'Sin Informacion')
University.create!(name: 'Universidad de Chile')
University.create!(name: 'Pontificia Universidad Católica de Chile')
University.create!(name: 'Universidad de Concepción')
University.create!(name: 'Pontificia Universidad Católica de Valparaíso')
University.create!(name: 'Universidad Austral de Chile')
University.create!(name: 'Universidad de Talca')
University.create!(name: 'Universidad Técnica Federico Santa María')
University.create!(name: 'Universidad de La Frontera')
University.create!(name: 'Universidad Diego Portales')
University.create!(name: 'Universidad Católica del Norte')
University.create!(name: 'Universidad Adolfo Ibáñez')
University.create!(name: 'Universidad Andrés Bello')
University.create!(name: 'Universidad de Santiago de Chile')
University.create!(name: 'Universidad del Bío-Bío')
University.create!(name: 'Universidad de Valparaíso')
University.create!(name: 'Universidad de los Andes')
University.create!(name: 'Universidad de Tarapacá')
University.create!(name: 'Universidad de La Serena')
University.create!(name: 'Universidad Alberto Hurtado')
University.create!(name: 'Universidad del Desarrollo')
University.create!(name: 'Universidad de Antofagasta')
University.create!(name: 'Universidad de Los Lagos')
University.create!(name: 'Universidad Mayor')
University.create!(name: 'Universidad Metropolitana de Ciencias de la Educación')
University.create!(name: 'Universidad Católica de Temuco')
University.create!(name: 'Universidad Tecnológica Metropolitana')
University.create!(name: 'Universidad de Magallanes')
University.create!(name: 'Universidad Arturo Prat')
University.create!(name: 'Universidad de Atacama')
University.create!(name: 'Universidad Católica de la Santísima Concepción')
University.create!(name: 'Universidad Católica del Maule')
University.create!(name: 'Universidad Santo Tomás')
University.create!(name: 'Universidad Central de Chile')
University.create!(name: 'Universidad San Sebastián')
University.create!(name: 'Universidad Adventista de Chile')
University.create!(name: 'Universidad de Playa Ancha')
University.create!(name: 'Universidad Finis Terrae')
University.create!(name: 'Universidad de Artes, Ciencias y Comunicación')
University.create!(name: 'Universidad Viña del Mar')
University.create!(name: 'Universidad Tecnológica de Chile Inacap')
University.create!(name: 'Universidad Católica Silva Henríquez')
University.create!(name: 'Universidad Academia de Humanismo Cristiano')
University.create!(name: 'Universidad de Artes y Ciencias Sociales')
University.create!(name: 'Universidad Autónoma de Chile')
University.create!(name: 'Universidad del Pacífico')
University.create!(name: 'Universidad de Las Américas')
University.create!(name: 'Universidad Gabriela Mistral')
University.create!(name: 'Universidad Bernardo OHiggins')
University.create!(name: 'Universidad Ciencias de la Informática')
University.create!(name: 'Universidad Internacional SEK')
University.create!(name: 'Universidad del Mar')
University.create!(name: 'Universidad Pedro de Valdivia')
University.create!(name: 'Universidad Bolivariana')
University.create!(name: 'Universidad Iberoamericana de Ciencias y Tecnología')
University.create!(name: 'Universidad La República')
University.create!(name: 'Universidad de Aconcagua')
University.create!(name: 'Universidad Los Leones')
University.create!(name: 'Universidad Chileno-Británica de Cultura')
University.create!(name: 'Universidad Miguel de Cervantes')
University.create!(name: 'Universidad La Araucana')